### ISSUE TITLE
Case 15

### ISSUE THREAD

**Issue by alicelg99** [TillF/wasa_tests#2]
We notice that if we delete all the files in the Ouput folder of the case 15, and then we run the code, just a file named **_parameter.out_** appears in the folder. So this case does not work. This is why we decide to do some tests that we can see on the table reported on the pdf file.

[tests_case15.pdf](https://github.com/TillF/wasa_tests/files/6746152/tests_case15.pdf)

**Comment by TillF** [comment]
How are you running the model? From the console, with a batch-file or using the R-wrapper? In any case, there should be a way to observe WASA's screen output to see what the matter is. In this case, it says:
Fortran runtime error: Cannot open file 'e:/till/uni/wasa/benchmarks/wasa_tests/15/.\Input\Others/transposition.dat': No such file or directory

Thus, this file is mandatory but missing, when transpositions are enabled. The error affects case 7 likewise.
Please create such file (see WASA-docu) and re-try. If this solves the problem, you may close this Issue.

**Comment by alicelg99** [comment]
I am running the code with the batch-file (file names Run_WASA.bat). Is WASA's screen output the file _**Protocol.txt**_ ?

**Comment by TillF** [comment]
I guess so. You can check where the output is piped to by looking into the contents of the run_wasa.bat.

**Comment by TillF** [comment]
Just discovered that case 15 also lacks lu2.dat, which is necessary for the snow module.

**Comment by alicelg99** [comment]
Yes with these two files this case works.
