### ISSUE TITLE
Case 7

### ISSUE THREAD

**Issue by alicelg99** [TillF/wasa_tests#3]
All the out files are empty for this case. I did the same thing as for case 15 to find the error but there is any error message. When executing the code on the terminal I get :

```
(base) G:\Documents\TestInput7>.\wasa.exe .\do.dat >> .\Protocol.txt

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0xffffffff
#1  0xffffffff
#2  0xffffffff
#3  0xffffffff
#4  0xffffffff
#5  0xffffffff
#6  0xffffffff
#7  0xffffffff
#8  0xffffffff
#9  0xffffffff
#10  0xffffffff
#11  0xffffffff
#12  0xffffffff
#13  0xffffffff
#14  0xffffffff
```

I attach the **_Protocol.txt_** I get.

[Protocol.txt](https://github.com/TillF/wasa_tests/files/6749072/Protocol.txt)

**Comment by TillF** [comment]
Please push the newest version of the test case, so I can debug this.

**Comment by alicelg99** [comment]
I did. The do.dat is updated and the Input folder is on the main page (because it is the same I used for each case).

**Comment by TillF** [comment]
There were errors in the transpostion.dat, that caused the model to crash. I added an error checking to WASA and fixed the file. I also
enabled reservoirs for case 7, as the transpositions should be tested with them, too. Please update the overview table accordingly.
Please update and test. It should now also run with the old executable, i.e. no need to update it. If OK, please close issue.

**Comment by alicelg99** [comment]
Ok, I will test it. I used the same transposition.dat for the case 15, do I have to use the new one for this case too ?

**Comment by TillF** [comment]
As  transposition.dat is now in Input_A, it should be valid for all runs with dotrans=TRUE, I think.

**Comment by alicelg99** [comment]
When I run the code with the new exe (rev273) but also with the old one (rev271). There is an error message saying that the file _**routing.dat**_ cannot be found while it exists. See below :

```
(base) G:\Documents\TEST>.\wasa.exe .\do.dat
WASA model, rev_273-0-g3c865f2
 repository date 2021-07-02 13:58:22 +0200, built Fri 12:24
 :Initialization
reading runtime parameters from ./do.dat                                                                                
 ./../Inputs/Input_A/maxdim.dat could not be opened. Using default dimensions specified in the source code.
 ./../Inputs/Input_A/outfiles.dat could not be opened. Using default output files.
Error: Input file ./../Inputs/Input_A/River/routing.dat not found, aborting.
```

**Comment by alicelg99** [comment]
You can ignore the previous comment because the case 7 works but I had to change the path for the folder (cf error Folder path). If it is ok for you I can close the issue.

**Comment by TillF** [comment]
OK, I'll close this now.
Btw, you can reference other issues just by typing something like #7 .
