### ISSUE TITLE
Snow files

### ISSUE THREAD

**Issue by alicelg99** [TillF/wasa_tests#6]
The case 15 is the case where the snow mode is on. That means some out files are specific to this case. I will write what I have noticed when going through these files. For some we get strange results that is why I create an 'Issue'.
First, it is important to notice that I changed the temperatures for January 2001 into the time series file _**temperature.dat**_. The data are :
```
Daily average temperature (in degree Celsius)
Date	No. of days	Subbasin-ID.
0	0	69	15
...
1012001	1	12.3	11.7
2012001	2	11.8	10.9
3012001	3	12.8	11.7
4012001	4	2.9	1.9
5012001	5	3.9	3
6012001	6	4.1	3.2
7012001	7	4.1	3.4
8012001	8	4	2.9
9012001	9	4.2	2.8
10012001	10	-3.9	-3
11012001	11	-3.8	-2.8
12012001	12	-4	-3.7
13012001	13	-4.7	-4.3
14012001	14	-5.6	-5.3
15012001	15	0.3	0.8
16012001	16	1.7	2.4
17012001	17	0.2	0.3
18012001	18	-0.7	-0.9
19012001	19	0.3	0.1
20012001	20	3.8	3.4
21012001	21	3.4	3
22012001	22	3.2	2.7
23012001	23	3	2.8
24012001	24	2.5	2.5
25012001	25	3.4	22.6
26012001	26	4.5	3.9
27012001	27	15.1	14.2
28012001	28	14.5	14.2
29012001	29	14.1	13.4
30012001	30	25	23.4
31012001	31	25.8	24
```

Now, let see what we found into the files:

- _snowWaterEquiv.out_ : 0 everywhere except for January 2001 where we get positive values. Each day the values are different.
- _snowTemp.out_ : We get 0°C everywhere but sometimes we have -0.99990E+04 °C. **This is strange.**
- _snowEnergyCont.out_ : We have 0 kJ/m2 everywhere except for January 2001 where we get NaN. **Is there a reason for that?**
- _snowCover.out_ : We get 0 everywhere except for some days and sub-basin during January 2001 where we get 0.10000E+01 : 
        -  days 10, 11, 12, 13 and 17 for sub-basin 15
        -  days 18 to 31 for sub-basins 15 and 69
        **What does it depend on?**

- _snowAlbedo.out_ : Every days we get 0.88 except from the 4th of January 2001 where the values are different each day but lower than 0.88. **Why do the changes start from the 4th of January?**
>**_Note:_** we noticed the same thing for the files fluxSens.out, fluxPrec.out, rateAlbe.out, fluxNetS.out and fluxNetL.out (these last two have NaN for values but the other have real values).

- _snow_storage.stat_start_ : All the values are equal to 0.
- _snow_storage.stat_ : We get values for the columns 'storage' and 'albedo' but NaN for 'energy'. This is consistent with what we saw in the previous files.
- _cloudFrac.out_ : We get NaN every day. **Is that normal?**

**Comment by TillF** [comment]
I fixed some bugs and added the missing "snow_params.ctl". Please update both repos (data and executable) and check which errors persist.

**Comment by alicelg99** [comment]
After updating both repos and running again the code, I get :
Same notes as before for the files :
- **_snowWaterEquiv.out_** (0 everywhere and positive values appear on the 10th of January) ✔️
- **_snowTemp.out_** ⁉️ 
- _**snow_storage.stat_start**_

The changes are :
- _**snowEnergyCont.out**_ : not NaN anymore for January 2001 we get values different from 0 from day 10. The values are between -0.1E+05 and 0.1E+06 kJ/m2. ✔️
- _**snowCover.out**_ : this is a little bit the same observation but the values 0.10000E+01 are not for the same days. ⁉️ We select the lines concerned : 
```
1 | Output file TC-wise areal fraction of snow cover (-)
2 | Year	Day	Timestep	Subbasin	LU	TC	value
4251 | 2001	20	1	15	1	3	 0.10000E+01
4252 | 2001	20	1	15	1	2	 0.10000E+01
4253 | 2001	20	1	15	1	1	 0.10000E+01
4254 | 2001	20	1	15	2	6	 0.10000E+01
4255 | 2001	20	1	15	2	5	 0.10000E+01
4257 | 2001	20	1	69	1	3	 0.10000E+01
4258 | 2001	20	1	69	1	2	 0.10000E+01
4259 | 2001	20	1	69	1	1	 0.10000E+01
4260 | 2001	20	1	69	2	6	 0.10000E+01
4261 | 2001	20	1	69	2	5	 0.10000E+01
4263 | 2001	21	1	15	1	3	 0.10000E+01
4265 | 2001	21	1	15	1	1	 0.10000E+01
4269 | 2001	21	1	69	1	3	 0.10000E+01
4270 | 2001	21	1	69	1	2	 0.10000E+01
4271 | 2001	21	1	69	1	1	 0.10000E+01
4275 | 2001	22	1	15	1	3	 0.10000E+01
4281 | 2001	22	1	69	1	3	 0.10000E+01
```

- **_snowAlbedo.out_** : now the changes start from day 10 (on January 2001) this is more consistant. ✔️
- **_snow_storage.stat_** : it is okay now, we don't have NaN for 'energy' anymore. ✔️
- _**cloudFrac.out**_ : We get positive values everyday which are between 0 and 1. ✔️

**Comment by TillF** [comment]
OK, just replying on the still-open topics:
- snowTemp.out: "-9999" is a flag for "not available", as snow temperature cannot be computed when there is no snow. However, its treatment was somewhat inconsistent, as it sometimes was zero, sometimes -9999. Will be fixed in upcoming release. I also refined the formatting of the output, so you may have to re-run the other cases, too, to be consistent.

- snow_storage.stat_start : All the values are equal to 0 --> is ok, when the model has no snow at the start.
- snowCover.out : The snow cover can range from 0 to 1, so all values within this range should be ok

Reopen the issue, if you feel something still needs to be treated.
