### ISSUE TITLE
Folder path

### ISSUE THREAD

**Issue by alicelg99** [TillF/wasa_tests#7]
There is an issue regarding the new disposition of the folders. When I use the **_do.dat_** with lines 2 and 3 such as : 
```
../Inputs/Input_A
./Output/
```
I get an error message telling me that the file **_routing.dat_** cannot be found even if the file exists. See below the message : 
```
WASA model, rev_273-0-g3c865f2
 repository date 2021-07-02 13:58:22 +0200, built Fri 12:24
 :Initialization
reading runtime parameters from ./do.dat                                                                                                                                                        
 ./../Inputs/Input_A/maxdim.dat could not be opened. Using default dimensions specified in the source code.
 ./../Inputs/Input_A/outfiles.dat could not be opened. Using default output files.
Error: Input file ./../Inputs/Input_A/River/routing.dat not found, aborting.
```

When I simply change the path as in the previous cases (Input and Output folders in the same folder), I don't get this error message.
This is maybe due to the path definition or because the input and output folders are not at the same place.

**Comment by TillF** [comment]
Strange, I cannot reproduce this error. I tried cases 1,2,11 and 12.
Which case are you using?
How do you start the executable, with the runme.bat, I assume?
Can you provide the exact command that is inside the bat-file? 
Does the same happen when you run the command directly from the command line or call it from Python?

**Comment by alicelg99** [comment]
This is what I get for case 1. Ans the same thing happen if I run it from the .bat file.
```
G:\Documents\TestInput1>.\wasa.exe .\do.dat
WASA model, rev_273-0-g3c865f2
 repository date 2021-07-02 13:58:22 +0200, built Fri 12:24
 :Initialization
reading runtime parameters from ./do.dat
 ./../Inputs/Input_A/maxdim.dat could not be opened. Using default dimensions specified in the source code.
 ./../Inputs/Input_A/outfiles.dat could not be opened. Using default output files.
Error: Input file ./../Inputs/Input_A/River/routing.dat not found, aborting.
```

**Comment by TillF** [comment]
Hm, here it runs smoothly.
Are you sure you are running this in the complete folder structure?
Judging from your call
"G:\Documents\TestInput1>.\wasa.exe .\do.dat"
The should be 
"G:\Documents\Inputs\Input_A"
Does this folder exist? That means, is 
G:\Documents\
really the base directory for your commits to "wasa_tests" with the complete folder structure? It doesn't seem so, as in the repo the test drectory is names "1", not "TestInput1".

**Comment by alicelg99** [comment]
This is because I am still using the old configuration. How do you run the executable with this disposition?

**Comment by TillF** [comment]
I suggest you copy the executable to 
[your path to wasas_tests]
and change to this directory.
From the console, you should then be able to run e.g.
wasa.exe 1\do.dat

**Comment by alicelg99** [comment]
Ok it works thank you.
