### ISSUE TITLE
svc.dat file

### ISSUE THREAD

**Issue by alicelg99** [TillF/wasa_tests#8]
The file **_svc.dat_** in _Input_A/Hillslope_ has a column named **irrigation** but it does not contains any data. See as follows : 
```
Specifications of soil vegetation components and erosion parameters
id	soil_id	veg_id	musle_k[(ton acre hr)/(acre ft-ton inch)]	musle_c[-]	musle_p[-]	coarse_fraction[%]	manning_n	irrigation
53	1016	45	0.166319584987491	8e-04	1	0.01689	0.2
55	1027	55	0.166319584987491	0.25	1	0.01689	0.14
57	1016	55	0.166319584987491	0.177	1	0.01689	0.177
```

Is that normal ?

**Comment by TillF** [comment]
This is something that Paul should better answer. Assigned to plvoit.

**Comment by plvoit** [comment]
Yes, that's normal. In the executable wer're using at the moment there is no irrigation module. The program ignores this column. When we test the model with irrgation module later, it'll be useful.
